### ISSUE TITLE
Gestionar Aula

### ISSUE THREAD

**Issue by KassieZuritaG** [diegoismael81/PryEjercicioNRC7618#4]

**Comment by KassieZuritaG** [comment]
Crear interfaz de servicio

**Comment by KassieZuritaG** [comment]
- [ ] Registro y conexión a la base de datos #4
- [ ]  Crear interfaz de servicio #4
- [ ]  Crear clase del servicio #4
- [ ]  Crear controlador (Create, Retrieve, Update, Delete, list ) #4
- [ ]  Confeccionar vista de formulario #4

**Comment by CindyProyectos** [comment]
- [x] Agregar funcionalidad de listado de Materia #4
 - [x] Agregar funcionalidad de crear de Materia #4
- [x] Agregar funcionalidad de actualizar de Materia #4
- [x] Agregar funcionalidad eliminar de Materia #4

**Comment by CindyProyectos** [comment]
- [x] Agregar funcionalidad de crear #4

**Comment by KassieZuritaG** [comment]
- [ ] Agregar funcionalidad de listado #4

**Comment by KassieZuritaG** [comment]
- [ ] Agregar funcionalidad eliminar @CindyProyectos #4

**Comment by CindyProyectos** [comment]
- [x] Agregar funcionalidad de listado #4

**Comment by CindyProyectos** [comment]
- [x] Agregar funcionalidad eliminar #4

**Comment by CindyProyectos** [comment]
- [x] Agregar funcionalidad de actualizar #4
